
version: '3.5'

services:
  ws-react-ui:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: ws-react-redux-ui-container
    image: local/ws-react-redux-ui-dev:latest
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000:3000"
    env_file: .env.localdev
