// Alert
export const ALERT__CLEAR = 'ALERT__CLEAR'
export const ALERT__FAILURE = 'ALERT__FAILURE'
export const ALERT__WARNING = 'ALERT__WARNING'
export const ALERT__INFORMATION = 'ALERT__INFORMATION'
export const ALERT__SUCCESS = 'ALERT__SUCCESS'

// Account
export const SIGNUP__REQUEST = Symbol('SIGNUP__REQUEST')
export const SIGNUP__SUCCESS = Symbol('SIGNUP__SUCCESS')
export const SIGNUP__FAILURE = Symbol('SIGNUP__FAILURE')

export const EMAIL_CONFIRMATION__REQUEST = Symbol('EMAIL_CONFIRMATION__REQUEST')
export const EMAIL_CONFIRMATION__SUCCESS = Symbol('EMAIL_CONFIRMATION__SUCCESS')
export const EMAIL_CONFIRMATION__FAILURE = Symbol('EMAIL_CONFIRMATION__FAILURE')

export const LOGIN__REQUEST = Symbol('LOGIN__REQUEST')
export const LOGIN__SUCCESS = Symbol('LOGIN__SUCCESS')
export const LOGIN__FAILURE = Symbol('LOGIN__FAILURE')

export const LOGOUT__REQUEST = Symbol('LOGOUT__REQUEST')
export const LOGOUT__SUCCESS = Symbol('LOGOUT__SUCCESS')
export const LOGOUT__FAILURE = Symbol('LOGOUT__FAILURE')

export const RECOVER_PASSWORD__REQUEST = Symbol('RECOVER_PASSWORD__REQUEST')
export const RECOVER_PASSWORD__SUCCESS = Symbol('RECOVER_PASSWORD__SUCCESS')
export const RECOVER_PASSWORD__FAILURE = Symbol('RECOVER_PASSWORD__FAILURE')

export const RESET_PASSWORD__REQUEST = Symbol('RESET_PASSWORD__REQUEST')
export const RESET_PASSWORD__SUCCESS = Symbol('RESET_PASSWORD__SUCCESS')
export const RESET_PASSWORD__FAILURE = Symbol('RESET_PASSWORD__FAILURE')

// User
export const LIST_USER__REQUEST = Symbol('LIST_USER__REQUEST')
export const LIST_USER__SUCCESS = Symbol('LIST_USER__SUCCESS')
export const LIST_USER__FAILURE = Symbol('LIST_USER__FAILURE')
